kind = "web"
previewPath = "/"
title = "APKMONZA"
version = "1.0.0"
id = "artifacts/apkmonza"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23122

[services.development]
run = "pnpm --filter @workspace/apkmonza run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/apkmonza", "run", "build" ]
publicDir = "artifacts/apkmonza/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23122"
BASE_PATH = "/"
